name: "Build"

# Workflow file for windows
on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y cmake qt6-base-dev

      - name: Running cmake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: motiv
          path: build/motiv
