name: "Build"

# Workflow file for windows
on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install Cmake
        uses: lukka/get-cmake@latest

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.*
      - name: Install OTF2
        run: |
          sudo apt-get update
          sudo apt-get install curl
          curl -o /tmp/otf2.tar.gz https://perftools.pages.jsc.fz-juelich.de/cicd/otf2/tags/otf2-3.0/otf2-3.0.tar.gz
          tar -xzf /tmp/otf2.tar.gz -C /tmp
          cd /tmp/otf2-3.0
          ./configure
          make
          sudo make install
          cd -

      - name: Running cmake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: motiv
          path: build/motiv
  MacOS:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install Cmake
        uses: lukka/get-cmake@latest

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.*
      - name: Install OTF2
        run: |
          brew install otf2

      - name: Running cmake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: motiv
          path: build/motiv
